# Generated by Django 5.1.5 on 2025-02-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
