# Generated by Django 5.1.5 on 2025-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_products_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_object',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
