# Generated by Django 5.1.5 on 2025-02-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
    ]
