# Generated by Django 5.1.5 on 2025-02-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_reviewrating_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
