# Generated by Django 5.1.5 on 2025-02-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_item_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='whishlist_object',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_object',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
