# Generated by Django 5.1.5 on 2025-02-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
    ]
