# Generated by Django 5.1.5 on 2025-02-28 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_coupon_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
