# Generated by Django 5.1.5 on 2025-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orderitem_coupon_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
