# Generated by Django 5.1.5 on 2025-03-04 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_reviewrating_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_object',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
