# Generated by Django 5.1.5 on 2025-03-04 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_orderitem_coupon_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
