# Generated by Django 5.1.5 on 2025-03-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_orderitem_coupon_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='coupon_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
