# Generated by Django 5.1.5 on 2025-03-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_basketitem_coupon_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='coupon_object',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_object',
        ),
    ]
